backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "status"
    label: "Status Komponenten"
    folder: "status-data"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Komponenten-Gruppe", name: "group", widget: "string"}
      - label: "Komponenten"
        name: "components"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Status", name: "status", widget: "select", options: ["operational", "degraded", "outage", "maintenance"]}
